name: Deploy App
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Sync Server
        run: |
          curl -X POST "https://voila-api.mmopro.in/sync-app" \
            -H "Content-Type: application/json" \
            -d '{"app": "btestapp1oct23-1761198341325", "repo": "https://github.com/BharatSharma34/btestapp1oct23-1761198341325.git", "github_token": "${{ secrets.GITHUB_TOKEN }}"}'